server {
    listen 80;

    location / {
        proxy_pass http://backend:5000;
    }

    # Nginx serves everything inside /static/ (css, js, images)
    location /static/ {
        alias /usr/share/nginx/html/static/;
        expires 30d;
    }
}